#!/usr/bin/env ruby

require 'shelly'
include Shelly

require 'fileutils'
include FileUtils


command 'cd',
    description: 'Changes the working directory.',
    usage: '\cd DIRECTORY' do |shell, argstring|
  argstring.strip!
  if argstring.length > 0
    argstring = File.expand_path argstring
    
    if File.exists?(argstring) and File.directory?(argstring)
      begin
        cd argstring
      rescue
        STDERR.puts "Error cding to #{argstring}."
      end
    else
      STDERR.puts "#{argstring} doesn't exist or isn't a directory."
    end
  else
    STDERR.puts "Must specify a directory to switch to."
  end
end

command 'gitx',
    description: 'Opens GitX.',
    usage: '\gitx' do |shell, argstring|
  system 'gitx'
end


prompt do |continuation|
  `git status &>/dev/null`
  is_git_repo = $? == 0
  
  if continuation
    prompt_char = '|'
  elsif is_git_repo
    prompt_char = "\u00b1"
  else
    prompt_char = '$'
  end
  
  if is_git_repo
    branch = nil
    `git branch`.each_line do |line|
      if line =~ /^\* (.*)$/
        branch = $1
      end
    end
    
    branch ||= '(???)'
    branch = ':' + branch
  else
    branch = ''
  end
  
  dir = File.basename(getwd)
  "[#{dir}#{branch}]#{prompt_char} "
end


shelly 'git'
